In [1]:
import numpy as np

In [4]:
Seq1 = 'TCATA'
Seq2 = 'TCCTA'

D = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
T = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
D, T

(array([[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]]))

In [11]:
for i in range(1, D.shape[0] ):
    for j in range(1, D.shape[1] ):        
        if Seq1[i-1] == Seq2[j-1]:
            sij = 1
        else:
            sij = 0
        D[i, j] = np.max( [ D[i-1, j-1] + sij , D[i-1, j]  , D[i, j-1] ] )
        T[i, j] = np.argmax( [ D[i-1, j-1] + sij , D[i-1, j]  , D[i, j-1] ] ) 
        # In T[i, j] cell 0: diagonal, 1: up, 2: left

In [12]:
print("Scroing Matrix...")
print(D)
print("Track Back Matrix...")
print(T)

Scroing Matrix...
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.]
 [ 0.  1.  2.  2.  2.  2.]
 [ 0.  1.  2.  2.  2.  3.]
 [ 0.  1.  2.  2.  3.  3.]
 [ 0.  1.  2.  2.  3.  4.]]
Track Back Matrix...
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  2.  0.  2.]
 [ 0.  1.  0.  0.  2.  2.]
 [ 0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  1.]
 [ 0.  1.  1.  0.  1.  0.]]


In [10]:
# Tracing with Trace Back Matrix
i = T.shape[0] - 1
j = T.shape[1] - 1
S1 = ''
S2 = ''
print("Scroing Matrix...")
print(D)
print("Track Back Matrix...")
print(T)

# Tracing with Trace Back Matrix
i = T.shape[0] - 1
j = T.shape[1] - 1
S1 = ''
S2 = ''
while i != 0 or j != 0:
    
    if T[i,j] == 0:

        S1 = Seq1[i-1] + S1
        S2 = Seq2[j-1] + S2
        i = i-1
        j = j-1
    elif T[i, j] == 1: # up
        S1 = Seq1[i-1] + S1
        S2 = ' ' + S2
        i = i-1        
    elif T[i, j] == 2: # left
        S1 = ' '+ S1
        S2 = Seq2[j-1] + S2
        j = j-1        
S1, S2, D[len(Seq1),len(Seq2)]


Scroing Matrix...
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.]
 [ 0.  1.  2.  2.  2.  2.]
 [ 0.  1.  2.  2.  2.  3.]
 [ 0.  1.  2.  2.  3.  3.]
 [ 0.  1.  2.  2.  3.  4.]]
Track Back Matrix...
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  2.  0.  2.]
 [ 0.  1.  0.  0.  2.  2.]
 [ 0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  1.]
 [ 0.  1.  1.  0.  1.  0.]]


('TCATA', 'TCCTA', 4.0)