##### Needleman Wunsch Algorithm: A Global Sequence Alignment Algorithm

Introduction to algorithm:-

- https://www.youtube.com/watch?v=aD4Cc4L3qW0

The needleman-wunsch algorithm is appropriate for finding the best alignment of two sequences which are 
1) of the similar length
2) Similar across their entire lengths


In [68]:
import numpy as np
import pprint
import pandas as pd

In [70]:
Seq1 = 'TCATA'
Seq2 = 'TCCTA'

match     = +5.0
mismatch  = -1.0
gap       = -2.0


In [79]:
D = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
T = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
D[0,0] = 0

penality = 0
for i in range(1,D.shape[0]):
    penality = penality + gap
    D[i, 0]  = penality
    D[0, i]  = penality


In [80]:
for i in range(1, D.shape[0] ):
    for j in range(1, D.shape[1] ):        
        if Seq1[i-1] == Seq2[j-1]:
            sij = match
        else:
            sij = mismatch
        D[i, j] = np.max( [ D[i-1, j-1] + sij , D[i-1, j] + gap , D[i, j-1] + gap] )
        T[i, j] = np.argmax( [ D[i-1, j-1] + sij , D[i-1, j] + gap , D[i, j-1] + gap] ) 
        # In T[i, j] cell 0: diagonal, 1: up, 2: left

In [81]:

D = pd.DataFrame(D)
D.columns = [' '] + [ele for ele in Seq2]
D['Seq1 Vs Seq2'] = [' '] + [ele for ele in Seq1]
D.set_index('Seq1 Vs Seq2')

print("Scoring Matrix...")
print(D)
print('Trace Back Matrix')
print(T)

Scoring Matrix...
           T     C    C     T     A Seq1 Vs Seq2
0   0.0 -2.0  -4.0 -6.0  -8.0 -10.0             
1  -2.0  5.0   3.0  1.0  -1.0  -3.0            T
2  -4.0  3.0  10.0  8.0   6.0   4.0            C
3  -6.0  1.0   8.0  9.0   7.0  11.0            A
4  -8.0 -1.0   6.0  7.0  14.0  12.0            T
5 -10.0 -3.0   4.0  5.0  12.0  19.0            A
Trace Back Matrix
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  2.  0.  2.]
 [ 0.  1.  0.  0.  2.  2.]
 [ 0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  2.]
 [ 0.  1.  1.  0.  1.  0.]]


In [27]:
# Tracing with Trace Back Matrix
i = T.shape[0] - 1
j = T.shape[1] - 1
S1 = ''
S2 = ''
print("Scroing Matrix...")
print(D)
print("Track Back Matrix...")
print(T)

# Tracing with Trace Back Matrix
i = T.shape[0] - 1
j = T.shape[1] - 1
S1 = ''
S2 = ''
while i != 0 or j != 0:
    
    if T[i,j] == 0:
#         print(D[i,j])
        S1 = Seq1[i-1] + S1
        S2 = Seq2[j-1] + S2
        i = i-1
        j = j-1
    elif T[i, j] == 1: # up
#         print('up')
#         print(D[i,j])
        S1 = Seq1[i-1] + S1
        S2 = ' ' + S2
        i = i-1        
    elif T[i, j] == 2: # left
#         print('left')
#         print(D[i,j])
        S1 = ' '+ S1
        S2 = Seq2[j-1] + S2
        j = j-1        
S1, S2, D[len(Seq1),len(Seq2)]

        
S1, S2, D[len(Seq1),len(Seq2)]

Scroing Matrix...
[[  0.  -2.  -4.  -6.  -8. -10.]
 [ -2.   5.   3.   1.  -1.  -3.]
 [ -4.   3.  10.   8.   6.   4.]
 [ -6.   1.   8.   9.   7.  11.]
 [ -8.  -1.   6.   7.  14.  12.]
 [-10.  -3.   4.   5.  12.  19.]]
Track Back Matrix...
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  2.  0.  2.]
 [ 0.  1.  0.  0.  2.  2.]
 [ 0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  2.]
 [ 0.  1.  1.  0.  1.  0.]]


('TCATA', 'TCCTA', 19.0)

In [18]:
Seq1 = 'TCTA'
Seq2 = 'TCCTA'

match     = +5.0
mismatch  = -1.0
gap       = -2.0

D = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
T = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
D[0,0] = 0

penality = 0
for i in range(1,D.shape[0]):
    penality = penality + gap
    D[i, 0]  = penality
    D[0, i]  = penality

for i in range(1, D.shape[0] ):
    for j in range(1, D.shape[1] ):        
        if Seq1[i-1] == Seq2[j-1]:
            sij = match
        else:
            sij = mismatch
        D[i, j] = np.max( [ D[i-1, j-1] + sij , D[i-1, j] + gap , D[i, j-1] + gap] )
        T[i, j] = np.argmax( [ D[i-1, j-1] + sij , D[i-1, j] + gap , D[i, j-1] + gap] ) 
        # In T[i, j] cell 0: diagonal, 1: up, 2: left

print("Scroing Matrix...")
print(D)
print("Track Back Matrix...")
print(T)

# Tracing with Trace Back Matrix
i = T.shape[0] - 1
j = T.shape[1] - 1
S1 = ''
S2 = ''
while i != 0 or j != 0:
    
    if T[i,j] == 0:
#         print(D[i,j])
        S1 = Seq1[i-1] + S1
        S2 = Seq2[j-1] + S2
        i = i-1
        j = j-1
    elif T[i, j] == 1: # up
#         print('up')
#         print(D[i,j])
        S1 = Seq1[i-1] + S1
        S2 = ' ' + S2
        i = i-1        
    elif T[i, j] == 2: # left
#         print('left')
#         print(D[i,j])
        S1 = ' '+ S1
        S2 = Seq2[j-1] + S2
        j = j-1        
S1, S2, D[len(Seq1),len(Seq2)]


Scroing Matrix...
[[  0.  -2.  -4.  -6.  -8.   0.]
 [ -2.   5.   3.   1.  -1.  -2.]
 [ -4.   3.  10.   8.   6.   4.]
 [ -6.   1.   8.   9.  13.  11.]
 [ -8.  -1.   6.   7.  11.  18.]]
Track Back Matrix...
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  2.  0.  1.]
 [ 0.  1.  0.  0.  2.  2.]
 [ 0.  0.  1.  0.  0.  2.]
 [ 0.  1.  1.  0.  1.  0.]]


('T CTA', 'TCCTA', 18.0)

In [66]:
Seq1 = 'TCTA'
Seq2 = 'TCCA'

match     = +5.0
mismatch  = -1.0
gap       = -2.0

D = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
T = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
D[0,0] = 0

penality = 0
for i in range(1,D.shape[0]):
    penality = penality + gap
    D[i, 0]  = penality
    D[0, i]  = penality

for i in range(1, D.shape[0] ):
    for j in range(1, D.shape[1] ):        
        if Seq1[i-1] == Seq2[j-1]:
            sij = match
        else:
            sij = mismatch
        D[i, j] = np.max( [ D[i-1, j-1] + sij , D[i-1, j] + gap , D[i, j-1] + gap] )
        T[i, j] = np.argmax( [ D[i-1, j-1] + sij , D[i-1, j] + gap , D[i, j-1] + gap] ) 
        # In T[i, j] cell 0: diagonal, 1: up, 2: left
print("Scroing Matrix...")
print(D)
print("Track Back Matrix...")
print(T)
# Tracing with Trace Back Matrix
i = T.shape[0] - 1
j = T.shape[1] - 1
S1 = ''
S2 = ''
while i != 0 or j != 0:
#     print(i,j)
    if T[i,j] == 0:
        S1 = Seq1[i-1] + S1
        S2 = Seq2[j-1] + S2
        i = i-1
        j = j-1
    elif T[i, j] == 1: # up
        S1 = Seq1[i-1] + S1
        S2 = ' ' + S2
        i = i-1        
    elif T[i, j] == 2: # left
        S1 = ' '+ S1
        S2 = Seq2[j-1] + S2
        j = j-1        
S1, S2, D[len(Seq1),len(Seq2)]


Scroing Matrix...
[[  0.  -2.  -4.  -6.  -8.]
 [ -2.   5.   3.   1.  -1.]
 [ -4.   3.  10.   8.   6.]
 [ -6.   1.   8.   9.   7.]
 [ -8.  -1.   6.   7.  14.]]
Track Back Matrix...
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  2.  2.  2.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  0.]]


('TCTA', 'TCCA', 14.0)

In [67]:
print(D, Seq1)
D = pd.DataFrame(D)
D.columns = [' '] + [ele for ele in Seq2]
D['Seq1 Vs Seq2'] = [' '] + [ele for ele in Seq1]
D.set_index('Seq1 Vs Seq2')

[[  0.  -2.  -4.  -6.  -8.]
 [ -2.   5.   3.   1.  -1.]
 [ -4.   3.  10.   8.   6.]
 [ -6.   1.   8.   9.   7.]
 [ -8.  -1.   6.   7.  14.]] TCTA


T     C    C     A
Seq1 Vs Seq2                           
              0.0 -2.0  -4.0 -6.0  -8.0
T            -2.0  5.0   3.0  1.0  -1.0
C            -4.0  3.0  10.0  8.0   6.0
T            -6.0  1.0   8.0  9.0   7.0
A            -8.0 -1.0   6.0  7.0  14.0