In [61]:
import numpy as np
import pprint

In [50]:
Seq1 = 'TCATA'
Seq2 = 'TCCTA'

match     = +5.0
mismatch  = -1.0
gap       = -2.0


In [66]:
D = np.zeros( (len(Seq1)+1, len(Seq2)+1 ) )
D[0,0] = 0

penality = 0
for i in range(1,D.shape[0]):
    penality = penality + gap
    D[i, 0]  = penality
    D[0, i]  = penality

In [65]:
for i in range(1, D.shape[0] ):
    for j in range(1, D.shape[1] ):        
        if Seq1[i-1] == Seq2[j-1]:
            sij = match
        else:
            sij = mismatch
        D[i, j] = np.max( [ D[i-1, j-1] + sij , D[i-1, j] + gap , D[i, j-1] + gap] )
print(D)


[[  0.  -2.  -4.  -6.  -8. -10.]
 [ -2.   0.   0.   0.   0.   0.]
 [ -4.   0.   0.   0.   0.   0.]
 [ -6.   0.   0.   0.   0.   0.]
 [ -8.   0.   0.   0.   0.   0.]
 [-10.   0.   0.   0.   0.   0.]]
[[  0.  -2.  -4.  -6.  -8. -10.]
 [ -2.   5.   3.   1.  -1.  -3.]
 [ -4.   3.  10.   8.   6.   4.]
 [ -6.   1.   8.   9.   7.  11.]
 [ -8.  -1.   6.   7.  14.  12.]
 [-10.  -3.   4.   5.  12.  19.]]
